---

title: kbairak's blog
email: ikijob@gmail.com
description: >-
  Mostly programming tips and tutorials, mostly in Python. But who knows? I may
  rumble about other things as well.
baseurl: ""
url: "https://kbairak.github.io"
twitter_username: kbairak
github_username: kbairak

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
